### ISSUE TITLE
Issue exporting against current version of Tutanota

### ISSUE THREAD

**Issue by knightsg** [crepererum/tatutanatata#34]
Thanks for creating this tool, it's been really useful! However, it seems like something changed in the most recent version(s) of Tutanota - when I try to export now I'm getting the following error:

ubuntu@ip-10-100-1-18:~/importer/tatutanatata$ cargo run --release -- -v export --folder Inbox
    Finished release [optimized] target(s) in 1.22s
     Running `target/release/tatutanatata -v export --folder Inbox`
2023-03-26T22:19:48.649634Z  INFO tatutanatata::commands::export: found mail list list_size=41 list_height=6868
2023-03-26T22:19:48.756158Z  INFO tatutanatata::commands::export: handle entry list_size=41 y=0
2023-03-26T22:19:50.956400Z  INFO tatutanatata::commands::export: handle entry list_size=41 y=68
Error: webdriver execution

Caused by:
    0: export
    1: export current main
    2: find action-bar
    3: expected exactly one element but got 0

I tried the export on a few other folders and got the same error.

**Comment by crepererum** [comment]
Yeah, tutanota changed their UI and I haven't had time to adjust the code yet. There's nothing we can do to prevent that (except getting them to finally implement mass export on their side).

I currently only have limited resources to work on this, so if someone wants to pick this up, feel free to do so.

**Comment by knightsg** [comment]
Yeah that's fair. Not sure if I have the skills but I'll take a look when I have some time and see if I can do anything to make it work.
